import React from 'react';
import { FieldWidgetProps } from './types';

/**
 * AutoNumberField - Read-only auto-generated field
 * Values are automatically generated by the system and cannot be edited
 */
export function AutoNumberField({ value, field, ...props }: FieldWidgetProps<string | number>) {
  const displayValue = value != null ? String(value) : '-';

  return (
    <span className={`text-sm font-mono text-gray-700 ${props.className || ''}`}>
      {displayValue}
    </span>
  );
}
