/**
 * ObjectUI — codegen the JSX type surface from the registry manifest (ADR-0080 §3)
 *
 * Emits a `.d.ts` that augments `JSX.IntrinsicElements` so a constrained
 * JSX-source page type-checks in `.tsx`: tag name === registry `type` key,
 * attributes === the component's manifest `inputs`. This is a TYPE-CHECKING
 * fiction — no real React intrinsic named `flex` exists; the interpreter
 * fulfills it via the registry at render time.
 */

import type { Manifest, ManifestComponent, ManifestInput, ManifestInputType } from './types.js';
import { inputTypeArms } from './input-type.js';

export interface CodegenOptions {
  /** include a self-contained minimal JSX namespace so the d.ts type-checks
   *  standalone (no React types needed). Default true. */
  standaloneJsx?: boolean;
}

export function generateDts(manifest: Manifest, options: CodegenOptions = {}): string {
  const { standaloneJsx = true } = options;
  const comps = Object.values(manifest.components).sort((a, b) => a.type.localeCompare(b.type));

  const interfaces = comps.map(emitInterface).join('\n\n');
  const intrinsics = comps
    .map((c) => `      ${JSON.stringify(c.type)}: ${propsName(c.type)};`)
    .join('\n');

  const baseElement = standaloneJsx
    ? `
    // minimal, so the surface type-checks without pulling React types
    type Element = unknown;
    interface ElementClass {}
    interface ElementAttributesProperty {}
    interface ElementChildrenAttribute { children: object; }`
    : '';

  return `// AUTO-GENERATED by @object-ui/sdui-parser — DO NOT EDIT.
// Source of truth: ComponentRegistry inputs (ADR-0080 §3). Regenerate via codegen.
/* eslint-disable */

export interface SduiBaseProps {
  id?: string;
  className?: string;
  style?: Record<string, unknown>;
  visible?: boolean;
  visibleOn?: string;
  disabled?: boolean;
  disabledOn?: string;
  children?: unknown;
}

${interfaces}

declare global {
  namespace JSX {
    interface IntrinsicElements {
${intrinsics}
    }${baseElement}
  }
}

export {};
`;
}

/**
 * A `'slot'` arm names a child position, not a prop value — `SduiBaseProps`
 * already types `children`, so a slot input contributes no attribute. An input
 * is therefore emitted when it has at least one NON-slot arm, and typed from
 * those arms only (objectui#3832): the old test was `i.type !== 'slot'`, which a
 * union like `['slot', 'string']` would have passed while `tsType` fell through
 * to the default and typed it `string` anyway.
 */
function emitInterface(comp: ManifestComponent): string {
  const lines = comp.inputs
    .filter((i) => valueArms(i).length > 0)
    .map((i) => `  ${propLine(i)}`)
    .join('\n');
  return `export interface ${propsName(comp.type)} extends SduiBaseProps {\n${lines}\n}`;
}

/** The arms that describe a VALUE (every arm except `'slot'`). */
const valueArms = (input: ManifestInput): ManifestInputType[] =>
  inputTypeArms(input.type).filter((arm) => arm !== 'slot');

function propLine(input: ManifestInput): string {
  const opt = input.required ? '' : '?';
  return `${quoteKeyIfNeeded(input.name)}${opt}: ${tsType(input)};`;
}

/**
 * The TypeScript type for one arm. Kinds that are a string with a narrower
 * authoring control (`color`, `date`, `code`, `file`) are `string` here, as
 * before — the JSX surface types the VALUE, and the control kind is the
 * designer's business.
 */
function armTsType(arm: ManifestInputType, input: ManifestInput): string {
  switch (arm) {
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return `${memberTsType(input)}[]`;
    case 'object':
      return `Record<string, ${memberTsType(input)}>`;
    case 'enum': {
      const vals = (input.enum ?? []).map((e) => (typeof e === 'object' ? e.value : e));
      return vals.length ? vals.map((v) => JSON.stringify(v)).join(' | ') : 'string';
    }
    default:
      return 'string';
  }
}

/**
 * The TypeScript type of a container's MEMBERS, from `ManifestInput.of`
 * (objectui#8067).
 *
 * `unknown` when nothing is declared, which is what every input published
 * before `of` existed says — so an undeclared array still emits `unknown[]` and
 * an undeclared object still emits `Record<string, unknown>`, byte for byte.
 * A declared member kind narrows it: `of: 'string'` on `page:header.actions`
 * turns `unknown[]` into `string[]`, and the JSX surface finally types the
 * action IDs the contract has always required.
 *
 * `'slot'` is dropped for the same reason {@link valueArms} drops it one level
 * up: it names a child position, not a value, so it contributes no member type.
 * If that leaves nothing, the result is `unknown` — a declaration that types no
 * member must not silently type them all as strings.
 */
function memberTsType(input: ManifestInput): string {
  const arms = inputTypeArms(input.of).filter((arm) => arm !== 'slot');
  if (arms.length === 0) return 'unknown';
  const emitted = [...new Set(arms.map((arm) => armTsType(arm, { ...input, of: undefined })))];
  return emitted.length === 1 ? emitted[0] : `(${emitted.join(' | ')})`;
}

/**
 * A union declaration emits a TypeScript union, so the `.d.ts` an author
 * type-checks their page against accepts exactly the arms the manifest gate
 * accepts. Arms that collapse to the same TS type (`string` and `color`, say)
 * are de-duplicated rather than emitted as `string | string`.
 */
function tsType(input: ManifestInput): string {
  const arms = valueArms(input);
  if (arms.length === 0) return 'string';
  const emitted = [...new Set(arms.map((arm) => armTsType(arm, input)))];
  return emitted.join(' | ');
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const quoteKeyIfNeeded = (name: string): string => (IDENT.test(name) ? name : JSON.stringify(name));

/** 'object-grid' -> 'ObjectGrid', 'record:details' -> 'RecordDetails' */
export function propsName(type: string): string {
  const pascal = type
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join('');
  return `${pascal}Props`;
}

/**
 * Generate the human-facing PUBLIC block list (the curated "清单") from a
 * manifest — a Markdown table. Derived, never hand-maintained (ADR-0046).
 *
 * The html tier's intrinsic elements (`tier: 'html'`, objectui#10735) are
 * listed in a section of their own, under their own count: they are in the
 * manifest because a `kind:'html'` page may author them, not because they are
 * curated blocks, and a single table would read them as the latter.
 */
export function generateBlockList(manifest: Manifest): string {
  const sorted = Object.values(manifest.components).sort((a, b) => a.type.localeCompare(b.type));
  const curated = sorted.filter((c) => c.tier !== 'html');
  const htmlTier = sorted.filter((c) => c.tier === 'html');
  const row = (c: ManifestComponent): string => {
    const req = c.inputs.filter((i) => i.required).map((i) => i.name);
    const binds = c.inputs.filter((i) => i.binding).map((i) => `${i.name}:${i.binding}`);
    return `| \`${c.type}\` | ${c.namespace ?? '—'} | ${c.isContainer ? '✓' : ''} | ${req.join(', ') || '—'} | ${binds.join(', ') || '—'} |`;
  };
  const header = ['| block | plugin | container | required props | bindings |', '|---|---|---|---|---|'];
  return [
    `# SDUI public blocks (${curated.length})`,
    '',
    '> Auto-generated from the registry `tier:\'public\'` set (ADR-0080). Do not edit by hand.',
    '',
    ...header,
    ...curated.map(row),
    ...(htmlTier.length
      ? [
          '',
          `## html tier intrinsic elements (${htmlTier.length})`,
          '',
          "> The intrinsic HTML tags a `kind:'html'` page may author (ADR-0081 §2), declared by the registry's `HTML_TIER_INTRINSICS` roster and marked `tier: 'html'` in the manifest. Not part of the curated vocabulary above.",
          '',
          ...header,
          ...htmlTier.map(row),
        ]
      : []),
    '',
  ].join('\n');
}
