/**
 * ObjectUI
 * Copyright (c) 2024-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * `ObjectSchemaMetadata` ↔ `@objectstack/spec` derivation guard (objectui#5362).
 *
 * The maintainer ruled (2026-08-20, on #5362) that the object document type
 * belongs to `@objectstack/spec` and objectui DERIVES it rather than keeping a
 * hand-written second declaration. The hand-written interface this replaced
 * declared none of `titleFormat` / `listViews` / `icon` — three keys the
 * shipped runtime reads — while declaring nine members nothing reads and the
 * spec does not know. This guard is the forcing function that keeps the
 * settlement settled:
 *
 *   1. The derivation is structural — `ObjectSchemaMetadata` is the spec's
 *      `ServiceObject` plus the measured client delta, nothing else. Reverting
 *      the alias to a hand-written interface fails the `Equal` assertion and
 *      the three-key fixture below.
 *   2. The three read-but-formerly-undeclared keys are admitted, at compile
 *      time (typed fixture) and at runtime (spec zod shape).
 *   3. The SPELLING is settled: camelCase `listViews` is declared; snake
 *      `list_views` is not a key of the document type or the spec schema.
 *      The runtime keeps a snake READ fallback for stored app data published
 *      before this settlement (never censused — objectstack#7917); that
 *      tolerance lives at the read sites and must NOT leak back into the
 *      declared type, which is what the `@ts-expect-error` below pins.
 *   4. The client-extension surface stays measured: every member must have a
 *      live runtime read. Growing `ObjectSchemaClientExtensions` fails the
 *      key-set assertion, forcing the promote-upstream / justify-here
 *      decision consciously (same forcing function as
 *      `object-view-spec-parity.test.ts`). At `@objectstack/spec` 17.3.0 that
 *      surface is EMPTY: `editMode`, its only member, was PROMOTED UPSTREAM —
 *      which is route one of this very guard, arriving on its own. The
 *      assertions below moved from "the spec must not declare it" to "the spec
 *      declares it and the delta no longer restates it", which is the same
 *      invariant (exactly one declaration of the key) read from the other side.
 *
 * When one of these fails, do NOT edit this file first. Decide whether the
 * key belongs upstream in `@objectstack/spec` (promote it — the #5362 route
 * for the three keys was exactly that, objectstack#10144) or is a genuine
 * objectui-only runtime read (add it to the extension with its read site).
 */
import { describe, it, expect } from 'vitest';
import { ObjectSchema as SpecObjectSchema } from '@objectstack/spec/data';
import type { ServiceObject } from '@objectstack/spec/data';
import type {
  ObjectSchemaMetadata,
  ObjectSchemaClientExtensions,
} from '../field-types.js';

// ── compile-time half ────────────────────────────────────────────────────────
// Compiled by `tsconfig.test.json` via this package's `type-check` script —
// see that file's header for why tests must be in a compiled project at all
// (objectstack#4074: `satisfies` contracts that no tsc invocation ever read).

type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B
  ? 1
  : 2
  ? true
  : false;
type Assert<T extends true> = T;
type Extends<A, B> = A extends B ? true : false;

// 1. Structural derivation — the alias IS spec type + client delta.
type _derivation = Assert<
  Equal<ObjectSchemaMetadata, ServiceObject & ObjectSchemaClientExtensions>
>;

// 4. The client delta stays exactly the measured set — and at 17.3.0 that set
// is EMPTY. `editMode` was the one member; the spec adopted it (measured:
// `ObjectSchema`'s accept set 42 → 43 keys, gained set exactly `['editMode']`,
// lost set empty, declared as the same `'page' | 'modal'` union), so the key is
// carried by `ServiceObject` now and restating it here would be the two-
// declarations fork this guard exists to prevent. The app-shell read
// (`utils/recordFormNavigation.ts`, routed by `AppContent`'s central
// `handleEdit` dispatcher) is unchanged and still typed — through the
// derivation instead of through the delta.
type _extensionSurface = Assert<
  Equal<keyof ObjectSchemaClientExtensions, never>
>;

// …and `editMode` really is reachable on the derived type, not merely absent
// from the delta. This is the half a `keyof … = never` assertion cannot state:
// an empty delta would read identically if the spec had NOT adopted the key,
// and the member would then be silently unwritable.
type _editModeStillTyped = Assert<
  Extends<{ name: string; fields: Record<string, never>; editMode: 'page' }, ObjectSchemaMetadata>
>;

// 2. The three keys #5362 measured as read-but-undeclared are admitted, and
// a typed document can carry `editMode` alongside them — carried by the spec's
// own `ServiceObject` since 17.3.0, no longer by a local delta member.
const derivedAdmitsTheThreeKeys: ObjectSchemaMetadata = {
  name: 'task',
  fields: {
    subject: { type: 'text', label: 'Subject', required: true },
  },
  icon: 'check-square',
  titleFormat: '${subject}',
  listViews: {
    all: { label: 'All Tasks', columns: ['subject'] },
  },
  editMode: 'page',
};

// 3. Snake `list_views` is NOT part of the declared surface. If this
// directive ever reports as unused, the snake spelling has leaked back into
// the type — that is a regression of the #5362 settlement, not a cleanup.
const snakeSpellingIsNotDeclared: ObjectSchemaMetadata = {
  name: 'task',
  fields: {},
  // @ts-expect-error -- `list_views` was never a spec key; the spec declares only camelCase `listViews` (#5362).
  list_views: {},
};

// ── runtime half ─────────────────────────────────────────────────────────────

/** Top-level keys of a zod object (same helper as the sibling parity guards). */
function shapeKeys(schema: unknown): string[] {
  const carrier = schema as { shape?: unknown; _def?: { shape?: unknown } };
  const shape = carrier?.shape ?? carrier?._def?.shape;
  const resolved = typeof shape === 'function' ? (shape as () => object)() : shape;
  return resolved && typeof resolved === 'object' ? Object.keys(resolved) : [];
}

describe('ObjectSchemaMetadata spec derivation (#5362)', () => {
  const keys = shapeKeys(SpecObjectSchema);

  it('reads a live spec shape (positive control for every absence below)', () => {
    // A broken import or an empty shape would make every `not.toContain`
    // below pass vacuously; pin the corpus first.
    expect(keys.length).toBeGreaterThan(30);
    expect(keys).toContain('name');
    expect(keys).toContain('fields');
  });

  it('declares the three keys the runtime reads: icon, titleFormat, listViews', () => {
    expect(keys).toContain('icon');
    expect(keys).toContain('titleFormat');
    expect(keys).toContain('listViews');
  });

  it('canonizes camelCase listViews — snake list_views is not a spec key', () => {
    expect(keys).not.toContain('list_views');
  });

  it('does not declare the nine members the retired hand-written interface invented', () => {
    // These were declared by the old mirror, read by nothing in this repo,
    // and absent from the spec document — dropping them followed the spec.
    for (const retired of [
      'extends',
      'triggers',
      'primary_key',
      'relationships',
      'name_field',
      'soft_delete',
      'audit_trail',
      'version',
      'cache',
    ]) {
      expect(keys).not.toContain(retired);
    }
    // The spelling sibling: the identity the old `name_field` member wanted
    // exists in the spec under its camelCase key.
    expect(keys).toContain('nameField');
  });

  it('DECLARES editMode — the spec adopted it at 17.3.0 and the client delta retired its copy', () => {
    // The prescription the previous version of this test carried ("If this
    // starts failing, the spec has adopted `editMode`: retire it from
    // `ObjectSchemaClientExtensions` and let the derivation carry it") has been
    // executed. This is its other half: the key must be present HERE, or the
    // retirement removed the declaration without anything replacing it.
    expect(keys).toContain('editMode');
  });

  it('accepts the whole document — editMode included — through the spec parse', () => {
    // Key presence is not value reachability: `editMode` could be declared and
    // still refuse `'page'`. The fixture is passed WHOLE, with no key stripped
    // out, which is the assertion that would have failed at 17.2.0.
    const parsed = SpecObjectSchema.safeParse(derivedAdmitsTheThreeKeys);
    expect(parsed.success).toBe(true);
    expect(parsed.data?.editMode).toBe('page');
  });

  it('still refuses an INVENTED client key by name — the strictness that made editMode a delta has not gone soft', () => {
    // The control for the two assertions above, and the reason they are not
    // vacuous. `ObjectSchema` is strict on unrecognized keys (objectstack#4001);
    // if it had instead been loosened to a passthrough, `editMode` would parse
    // green for a reason that has nothing to do with adoption and this file
    // would report a settlement that did not happen.
    const parsed = SpecObjectSchema.safeParse({
      ...derivedAdmitsTheThreeKeys,
      editModeX: 'page',
    });
    expect(parsed.success).toBe(false);
    if (parsed.success) return;
    const unrecognized = parsed.error.issues.find(
      (issue) => issue.code === 'unrecognized_keys',
    );
    expect(unrecognized).toBeDefined();
    expect(
      (unrecognized as { keys?: string[] } | undefined)?.keys,
    ).toEqual(['editModeX']);
  });

  it('keeps the compile-time fixtures alive', () => {
    expect(derivedAdmitsTheThreeKeys.listViews).toBeDefined();
    expect(derivedAdmitsTheThreeKeys.icon).toBe('check-square');
    expect(derivedAdmitsTheThreeKeys.titleFormat).toBe('${subject}');
    expect(snakeSpellingIsNotDeclared.name).toBe('task');
  });
});
