/**
 * ObjectUI
 * Copyright (c) 2024-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * Auto-Layout for ObjectForm
 *
 * Provides intelligent, zero-configuration default layout for metadata-driven forms.
 * When the user has not explicitly set columns/colSpan/sections, this module
 * infers optimal layout based on field count and field types.
 *
 * Priority: User configuration > Auto-layout inference
 */

import type { FormField } from '@object-ui/types';

/** FormField types that are computed/aggregate and must be excluded from modal edit/create forms */
const AUTO_GENERATED_FORM_TYPES = new Set([
  'field:formula',
  'field:summary',
  'field:auto_number',
  'field:autonumber',
  // NOTE: 'field:master_detail' is NOT excluded here. From the child's perspective,
  // a master-detail field is the FK lookup to its parent and is typically required
  // (NOT NULL in the database). It must appear in create/edit forms as a lookup picker.
  // The "embedded sublist on parent detail page" use-case is rendered separately
  // via related-list views, not via the master-detail field type itself.
]);

/**
 * Field types that should span full width in multi-column layouts.
 *
 * Two spellings per type on purpose: the `field:` entries are the widget ids
 * `mapFieldTypeToFormType` produces (what a resolved `FormField.type` carries),
 * the BARE entries are `@objectstack/spec` `FieldType` names — app-shell's
 * `ObjectFormDesigner` passes a raw `objectDef.fields[x].type` straight in.
 * Both are matched RAW, so a bare member that is not a spec type name — and a
 * `field:` member that is not a registered widget id — silently matches
 * nothing.
 *
 * That is what `rich-text` / `field:rich-text` were: the spec spells the type
 * `richtext` (widget `field:richtext`) and REJECTS `rich-text`, which survives
 * only as a typo key in the spec's own `suggestFieldType` table. The set never
 * widened a rich-text field while `markdown` and `html` beside it did, and the
 * detail view's twin set had the identical hole — so the same field read wide
 * in neither surface (#4250). The dead spellings are dropped rather than kept
 * alongside: the alias table is the one place aliases belong.
 *
 * `grid` is NOT a spec `FieldType` — it is a sanctioned objectui-local key
 * (`GridFieldMetadata` in `@object-ui/types`), which is why it is exempt from
 * the spec-name pin in the tests.
 */
const WIDE_FIELD_TYPES = new Set([
  'field:textarea',
  'field:markdown',
  'field:html',
  'field:grid',
  'field:richtext',
  'textarea',
  'markdown',
  'html',
  'grid',
  'richtext',
]);

/**
 * Object field types that are auto-generated/aggregate and should be excluded
 * from modal edit/create forms — they are either computed server-side or render
 * as full-page sub-tables that belong on detail views, not dialogs.
 *
 * NOTE: master_detail/masterDetail are NOT excluded here. From the child-side
 * the field is the FK lookup to the parent (often required / NOT NULL); it must
 * appear in create/edit forms as a lookup picker. The "embedded sublist on the
 * parent's detail page" pattern is rendered by related-list views, not by this
 * field type.
 */
const AUTO_GENERATED_FIELD_TYPES = new Set([
  'formula',
  'summary',
  'auto_number',
  'autonumber',
]);

/**
 * Check if a field type is "wide" (should span full row in multi-column layout).
 */
export function isWideFieldType(type: string): boolean {
  return WIDE_FIELD_TYPES.has(type);
}

/**
 * Check if an object field type is auto-generated (formula, summary, auto_number).
 */
export function isAutoGeneratedFieldType(type: string): boolean {
  return AUTO_GENERATED_FIELD_TYPES.has(type);
}

/**
 * Infer the MAX column count from the field count (#2578). This is an UPPER
 * BOUND — the actual column count at render time is decided by the CSS
 * container queries in {@link CONTAINER_GRID_COLS} against the form's REAL
 * width, so a narrow drawer stays 1–2 columns while the SAME form on a wide
 * page spreads out to this cap. The cap scales with field count so a light
 * form is never thinned across too many columns, while a field-heavy record
 * can use the full width.
 *
 * Rules (upper bound; container queries clamp to the actual width):
 * - 0–3 fields  → 1 column
 * - 4–8 fields  → 2 columns
 * - 9–15 fields → 3 columns
 * - 16+ fields  → 4 columns
 */
export function inferColumns(fieldCount: number): number {
  if (fieldCount <= 3) return 1;
  if (fieldCount <= 8) return 2;
  if (fieldCount <= 15) return 3;
  return 4;
}

/** Clamp a raw column-ish number into 1..4 (the grid keys we support). */
function clampGrid(n: number | undefined): number {
  return n && n > 0 ? Math.min(Math.floor(n), 4) : 1;
}

/**
 * Resolve the effective colSpan (grid cells) a field occupies, given the form's
 * grid width and the section's desired column count (#2578).
 *
 * The column count is derived per surface (mobile 1 / modal 2 / page 3-4), so
 * the robust field-width primitive is the relative `span`, NOT an absolute
 * colSpan. Precedence:
 *   1. `span: 'full'`     → whole row (grid cells).
 *
 * ⚠️ «Whole row» is a claim about what RENDERS, and this function only returns
 * a number. It is kept by the form renderer's `spanLadderFor`, which turns
 * that number into one col-span class per container-query tier. Until
 * objectui#9244 the renderer emitted a single class for the widest tier only,
 * so this sentence was true of the return value and false on screen at every
 * intermediate width. ⛔ A pin under this function cannot observe that — see
 * `__tests__/spanFullTierLadder-9244.test.tsx` for the leg that can.
 *
 *   2. legacy `colSpan`   → honoured but CLAMPED to the grid (never overflows).
 *   3. wide widget type   → whole row (textarea/markdown/… — the `span:'auto'` default).
 *   4. section density    → grid / sectionColumns, so `sectionColumns` fields fill a row.
 *
 * `sectionColumns` defaults to the grid width, i.e. one field per cell (the flat
 * form's historical behaviour) when there is no narrower section.
 */
export function resolveColSpan(
  field: FormField,
  gridColumns: number,
  sectionColumns?: number,
): number {
  const grid = clampGrid(gridColumns);
  if (grid <= 1) return 1;

  const span = (field as { span?: 'auto' | 'full' }).span;
  if (span === 'full') return grid;

  // Legacy absolute colSpan — honoured but clamped so it can never overflow the
  // current grid (the fragility `span` exists to replace).
  if (field.colSpan != null) {
    return Math.min(Math.max(1, Math.floor(field.colSpan)), grid);
  }

  // `span: 'auto'` (or unset): wide widgets take the whole row.
  if (field.type && isWideFieldType(field.type)) return grid;

  // Otherwise fill the section's density: N per row → grid/N cells each.
  const secCols = Math.min(Math.max(1, Math.floor(sectionColumns || grid)), grid);
  return Math.min(grid, Math.max(1, Math.round(grid / secCols)));
}

/**
 * Apply the resolved colSpan to each field so the form's CSS grid lays them out
 * at the intended density. Span-aware and clamping (#2578); wide fields still
 * span the full row (the `span: 'auto'` default). `section-divider` rows are
 * left untouched (they carry their own full-row span).
 *
 * @param gridColumns    The form's grid column count (1-4).
 * @param sectionColumns The desired columns for THIS group of fields (defaults
 *                       to the grid width = one field per cell).
 * @returns A new array of fields with colSpan applied where needed.
 */
export function applyAutoColSpan(
  fields: FormField[],
  gridColumns: number,
  sectionColumns?: number,
): FormField[] {
  const grid = clampGrid(gridColumns);
  if (grid <= 1) return fields;

  return fields.map(field => {
    if ((field as { type?: string }).type === 'section-divider') return field;
    const eff = resolveColSpan(field, grid, sectionColumns);
    if (eff > 1) return { ...field, colSpan: eff };
    // eff === 1: strip any stale larger colSpan so it doesn't overflow a
    // narrower grid than the author imagined.
    if (field.colSpan != null && field.colSpan !== 1) return { ...field, colSpan: 1 };
    return field;
  });
}

/**
 * System field names that are always auto-managed by the platform
 * (record identity + audit timestamps) and should never appear on
 * create/edit forms regardless of how they are declared on the schema.
 */
const SYSTEM_FIELD_NAMES = new Set([
  'id',
  'created_at',
  'createdAt',
  'updated_at',
  'updatedAt',
  'last_modified_at',
  'lastModifiedAt',
  'deleted_at',
  'deletedAt',
  'created_by',
  'createdBy',
  'updated_by',
  'updatedBy',
  'last_modified_by',
  'lastModifiedBy',
  'organization_id',
  'organizationId',
  'org_id',
  'orgId',
  'tenant_id',
  'tenantId',
  'owner',
  'owner_id',
  '_version',
  '_rev',
]);

/**
 * Filter out auto-managed system fields (id, audit timestamps, tenant/owner ids).
 * Applied in BOTH create and edit modes, because these fields are always
 * server-populated and rendering them as inputs (even when disabled) just
 * clutters the form. The detail page surfaces the audit metadata via
 * `RecordMetaFooter`.
 */
export function filterSystemFields(
  fields: FormField[],
  objectSchema?: any,
): FormField[] {
  return fields.filter((field) => {
    if (SYSTEM_FIELD_NAMES.has(field.name)) return false;
    const objField = objectSchema?.fields?.[field.name];
    // Honor `hidden: true` — internal/system fields (e.g. database_url,
    // metadata JSON blobs) must never surface as editable inputs in an
    // auto-generated form. The list grid (ObjectGrid) and detail drawer
    // already drop hidden fields; the auto-form is the one place that did
    // not, which leaked e.g. sys_environment.metadata as a raw JSON
    // textarea into the edit dialog. Applied in create AND edit.
    if (objField?.hidden === true) return false;
    // Also drop fields the schema explicitly marks readonly — these are
    // platform-managed (e.g. id alias, formula result columns).
    if (objField?.readonly === true) return false;
    return true;
  });
}

/**
 * Filter out auto-generated/readonly fields for create/edit mode.
 *
 * Dropped:
 * - `formula`, `summary`, `autonumber`, `master_detail` field types (server-computed).
 * - Fields with `readonly: true` on the object schema (e.g. `id`, `created_at`).
 * - Well-known system field names (id, created_at/createdAt, updated_at/updatedAt, etc.),
 *   even when the schema omits `readonly` — these are always platform-managed.
 *
 * Callers can force a readonly field back into the form by marking it
 * `hidden: false, readonly: false` in FormField overrides.
 *
 * @param fields - The form fields array
 * @param objectSchema - The object schema with original field metadata
 * @returns Filtered fields array
 */
export function filterCreateModeFields(
  fields: FormField[],
  objectSchema?: any
): FormField[] {

  return fields.filter(field => {
    // Drop well-known system-managed fields by name (id, created_at, updated_at, …).
    if (SYSTEM_FIELD_NAMES.has(field.name)) return false;

    // Check FormField.type directly (mapped type like 'field:formula')
    if (field.type && AUTO_GENERATED_FORM_TYPES.has(field.type)) return false;

    // Check against object schema field type + readonly flag
    if (!objectSchema?.fields) return true;
    const objField = objectSchema.fields[field.name];
    if (!objField) return true; // keep fields not in schema (custom fields)

    // Drop fields the schema declares as readonly — they are auto-managed.
    if (objField.readonly === true) return false;

    return !isAutoGeneratedFieldType(objField.type);
  });
}

/**
 * Filter auto-generated computed fields (formula, summary, etc.) — applied in
 * CREATE mode only. In edit mode these fields remain visible so users can see
 * their current computed values rendered as readonly.
 */
export function filterAutoGeneratedFields(
  fields: FormField[],
  objectSchema?: any,
): FormField[] {
  return fields.filter((field) => {
    if (field.type && AUTO_GENERATED_FORM_TYPES.has(field.type)) return false;
    const objField = objectSchema?.fields?.[field.name];
    if (!objField) return true;
    return !isAutoGeneratedFieldType(objField.type);
  });
}

/**
 * Container-query-based grid classes for laying out form FIELDS inside a
 * section. Uses `@container` / `@md:` / `@2xl:` / `@4xl:` variants so the grid
 * responds to the form's actual width (modal / drawer / split panel) instead of
 * the viewport — a narrow modal stays single-column regardless of viewport size.
 *
 * `1` maps to `undefined` so the caller falls back to the form renderer's
 * default single-column stack (`space-y-4`).
 */
export const CONTAINER_GRID_COLS: Record<number, string | undefined> = {
  1: undefined,
  2: 'grid gap-4 grid-cols-1 @md:grid-cols-2',
  3: 'grid gap-4 grid-cols-1 @md:grid-cols-2 @2xl:grid-cols-3',
  4: 'grid gap-4 grid-cols-1 @md:grid-cols-2 @2xl:grid-cols-3 @4xl:grid-cols-4',
};

/** Clamp an arbitrary column count into the 1–4 keys of {@link CONTAINER_GRID_COLS}. */
export function containerGridColsFor(columns: number | undefined): string | undefined {
  const cols = columns && columns > 0 ? Math.min(Math.floor(columns), 4) : 1;
  return CONTAINER_GRID_COLS[cols];
}

/**
 * Build the layout-related props for a *section's* inner form (`SchemaRenderer`).
 *
 * A section groups its fields and lays them out in `columns` columns. That grid
 * must be applied to the FIELD container INSIDE the form — not wrapped around
 * the whole form element. Wrapping the single `<form>` in a multi-column grid
 * (as the section variants used to) puts the entire form in the first grid cell
 * and leaves every other column permanently empty. Here we instead thread
 * `columns` + `fieldContainerClass` into the form so its own field container
 * becomes the multi-column grid — mirroring the flat-fields layout path.
 *
 * @param fields  Already-built (and permission-filtered) section fields.
 * @param columns Section column count (1–4).
 */
export function sectionFormLayout(
  fields: FormField[],
  columns: number | undefined,
): { fields: FormField[]; columns: number; fieldContainerClass?: string } {
  const cols = columns && columns > 1 ? Math.min(Math.floor(columns), 4) : 1;
  const laidOut = cols > 1 ? applyAutoColSpan(fields, cols) : fields;
  const fieldContainerClass = containerGridColsFor(cols);
  return {
    fields: laidOut,
    columns: cols,
    ...(fieldContainerClass ? { fieldContainerClass } : {}),
  };
}

/**
 * Infer an appropriate modal size based on the number of layout columns.
 * Used to auto-upgrade the modal width when auto-layout detects multi-column forms.
 *
 * Mapping:
 * - 1 column   → 'default' (max-w-lg)
 * - 2 columns  → 'xl'      (max-w-5xl)
 * - 3+ columns → 'full'    (max-w-[95vw])
 */
export function inferModalSize(columns: number): 'sm' | 'default' | 'lg' | 'xl' | 'full' {
  if (columns <= 1) return 'default';
  if (columns === 2) return 'xl';
  return 'full';
}

/**
 * Main auto-layout orchestrator.
 * Applies intelligent defaults only when the user has not explicitly configured layout.
 *
 * @param formFields - Generated form fields
 * @param objectSchema - The original object schema (with field types)
 * @param schemaColumns - User-provided columns (from ObjectFormSchema)
 * @param mode - Form mode ('create' | 'edit' | 'view')
 * @returns Object with processed fields and inferred columns
 */
export function applyAutoLayout(
  formFields: FormField[],
  objectSchema: any,
  schemaColumns: number | undefined,
  mode: string | undefined
): { fields: FormField[]; columns: number | undefined } {
  let fields = [...formFields];

  // Step 1a: Always drop platform-managed system fields (id, audit timestamps,
  // tenant ids, etc.) from create AND edit forms. They're populated by the
  // driver/security plugin, and the detail page surfaces audit metadata via
  // RecordMetaFooter — so showing them as (disabled) inputs is pure clutter.
  fields = filterSystemFields(fields, objectSchema);

  // Step 1b: In create mode, additionally drop formula/summary/auto-number
  // fields (server-computed). In edit mode keep them so users can see their
  // current computed values, typically rendered as readonly.
  if (mode === 'create') {
    fields = filterAutoGeneratedFields(fields, objectSchema);
  }

  // Step 2: If user explicitly set columns, respect it but still apply auto colSpan
  if (schemaColumns !== undefined) {
    fields = applyAutoColSpan(fields, schemaColumns);
    return { fields, columns: schemaColumns };
  }

  // Step 3: Infer columns from field count
  const columns = inferColumns(fields.length);

  // Step 4: Apply auto colSpan for wide fields
  fields = applyAutoColSpan(fields, columns);

  return { fields, columns };
}
