/**
 * ObjectUI
 * Copyright (c) 2024-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useContext } from 'react';
import { ComponentRegistry, elementDataSourceBlock, type ComponentInput } from '@object-ui/core';
import {
  ElementDataSourceGate,
  SchemaRendererContext,
  noDataSourceMessage,
  useResolvedDataSource,
  type ElementDataSourceMapping,
} from '@object-ui/react';
import type { DataSource } from '@object-ui/types';
import { ObjectForm } from './ObjectForm';
import { hasInlineFieldSource } from './submitTarget';

export { ObjectForm };
export type { ObjectFormComponentProps } from './ObjectForm';

/**
 * @deprecated Use `ObjectFormComponentProps`. Renamed in objectui#4650 because
 * `@objectstack/spec/ui` owns `ObjectFormProps` from 17.0.0, where it means the
 * AUTHORED props document of the `object-form` element — not this component's
 * props. The alias denotes the SAME type and is kept only so existing importers
 * keep compiling.
 */
export type { ObjectFormComponentProps as ObjectFormProps } from './ObjectForm';
export { FormSectionContainer } from './FormSection';
export type { FormSectionContainerProps } from './FormSection';
export {
  applyAutoLayout,
  inferColumns,
  inferModalSize,
  isWideFieldType,
  isAutoGeneratedFieldType,
  applyAutoColSpan,
  containerGridColsFor,
  filterCreateModeFields,
  filterSystemFields,
  filterAutoGeneratedFields,
} from './autoLayout';
export { TabbedForm } from './TabbedForm';
export type { TabbedFormProps, TabbedFormSchema, FormSectionConfig } from './TabbedForm';
export { WizardForm } from './WizardForm';
export type { WizardFormProps, WizardFormSchema, WizardStepConfig } from './WizardForm';
export { SplitForm } from './SplitForm';
export type { SplitFormProps, SplitFormSchema } from './SplitForm';
export { DrawerForm } from './DrawerForm';
export type { DrawerFormProps, DrawerFormSchema } from './DrawerForm';
export { ModalForm } from './ModalForm';
export type { ModalFormProps, ModalFormSchema } from './ModalForm';
export { EmbeddableForm } from './EmbeddableForm';
export type { EmbeddableFormProps, EmbeddableFormConfig, EmbeddableFormTexts } from './EmbeddableForm';
export { FormAnalytics } from './FormAnalytics';
export type { FormAnalyticsProps, FormSubmissionMetric } from './FormAnalytics';
export { MasterDetailForm } from './MasterDetailForm';
export type {
  MasterDetailFormProps,
  MasterDetailFormSchema,
  MasterDetailDetailConfig,
} from './MasterDetailForm';
export { LineItemsPanel } from './LineItemsPanel';
export type { LineItemsPanelSchema } from './LineItemsPanel';
export { deriveDetail, deriveColumns, deriveFormFields, findRelationshipField, resolveInlineMode } from './deriveMasterDetail';
export type { DerivedDetail, InlineMode, ChildObjectSchemaLike } from './deriveMasterDetail';

/**
 * The CREATE-payload rule this package owns, published for the OTHER form
 * renderer (objectui#6059).
 *
 * `omitServerResolvedDefaults` is a pure function over a values object and an
 * object schema — no React, no registry, no container — and it is the
 * COMPOSITION of two `@object-ui/core` predicates (`isRuntimeDefault` AND
 * `isMissingForRequired`, on create only) rather than a third opinion about
 * either. It stayed module-private through the whole #4047 / #4068 / #4069 /
 * #4085 / #5683 / #5727 / #5883 chain, so the console's `FormPage` — the SECOND
 * form renderer in this repo — had to spell that composition out by hand for
 * #5883, and the next renderer would have had to as well. Neither PREDICATE was
 * ever copied (both live in `@object-ui/core` precisely so they cannot fork),
 * but two hand-written copies of the composition are still free to disagree
 * about a case neither author had in mind. One importable function is not.
 *
 * `isRequiredInForm` travels with it because each one's docblock names the
 * other as its half: excusing a server-owned field from `required` and then
 * submitting the key anyway is not half a fix, it is no fix. A consumer able to
 * reach one and not the other can build exactly that state, which is the defect
 * #4069 and #5883 closed on the two chains separately.
 *
 * Deliberately NOT the rest of `schemaDefaults.ts`. `seedCreateValues`,
 * `schemaDefaultValues`, `isSeedableDefault`, `isCreateFormMode` and
 * `SeedContext` are adjacent, not asked for — no consumer outside this package
 * has needed them, and every added name is published surface somebody then has
 * to keep. `isRuntimeDefault` stays out for a stronger reason: it is
 * `@object-ui/core`'s to publish, this module only re-exports it for its own
 * call sites, and a second published spelling of one classifier is the very
 * thing #4085 collapsed.
 */
export { omitServerResolvedDefaults, isRequiredInForm } from './schemaDefaults';

/**
 * The `form.sections[].group` RESOLVER, published for the third form-section
 * consumer (objectui#8641).
 *
 * `resolveSectionGroupReferences` replaces every `{ group: 'x' }` section with
 * the section that group declares, and returns its input UNCHANGED — the same
 * array reference — when no section uses the reference form. It is a pure
 * function over plain data: no React, no registry, no container.
 *
 * ## Why it is published rather than copied
 *
 * `apps/console`'s `FormPage` has its OWN section builder (`buildSections`),
 * on none of this package's code path, and it read `sec.fields ?? []` — so a
 * spec-legal `{ group }` section produced a section with no label and no
 * fields, measured in the DOM as an empty bordered card with zero inputs on
 * both the internal `/forms/:name` and public `/f/:slug` routes. That is the
 * silent-drop class objectui#7051 closed HERE, arriving at a renderer #7051's
 * fix could not reach.
 *
 * The standing constraint of objectui#7051 / objectstack#13855 is that no
 * assembly rule may be re-implemented on the objectui side — not declared
 * order, not the empty-group drop, not the ungrouped trailing bucket, not the
 * collapse / `visibleWhen` passthrough. Every one of those comes from
 * `deriveFieldGroupLayout` (ADR-0085 §5) through this package's ONE adapter,
 * `deriveFieldGroupSections`, which this resolver calls. A consumer that
 * reached for `deriveFieldGroupLayout` directly would have to re-spell the
 * `collapse` enum -> `{ collapsible, collapsed }` mapping and the `visibleWhen`
 * passthrough to land on a section shape, which is that constraint's exact
 * prohibition. So the importable resolver is the only arm that keeps one
 * assembler and one behaviour for all three consumers.
 *
 * This is the same surface decision as objectui#6059's create-payload pair,
 * for the same file, and it is deliberately as small: the resolver and the
 * options type its signature requires (objectui#7324's rule — a consumer must
 * be able to NAME what it passes; a type adds no runtime surface).
 * `hasSectionGroupReference` stays module-private because the resolver already
 * answers it by returning its input unchanged, and `resetSectionGroupReports`
 * stays private because it is this package's own test seam.
 */
export { resolveSectionGroupReferences } from './sectionGroups';
export type { ResolveSectionGroupsOptions } from './sectionGroups';

/**
 * The field name a section entry resolves to — the identity rule of the three
 * entry shapes `ObjectFormSection.fields` declares, spelled once
 * (objectui#11615): a bare string is the name, the form view's `{ field }`
 * entry names its field by `field`, an inline `FormField` by `name`;
 * `undefined` when the entry names nothing.
 *
 * Published beside the resolver because the resolver RETURNS that union, and
 * objectui#7324's rule applies to reading what a published function hands
 * back as much as to naming what it takes: a consumer narrowing an entry by
 * hand reads `.name` off a `{ field }` entry — the second dialect this one
 * spelling exists to prevent. A pure function over plain data.
 */
export { sectionEntryName } from './sectionFields';

/**
 * The parameter types those published signatures require, so a consumer can
 * NAME what it must pass (objectui#7324).
 *
 * Both were unnameable: `ChildObjectSchemaLike` is the `childSchema` of the
 * five derive functions exported above, and `FieldDefaultsSchemaLike` is the
 * `objectSchema` of `omitServerResolvedDefaults`. Neither reached this barrel,
 * so a host held them in a variable it could not annotate and wrote the shape
 * out by hand instead — a producer-owned shape copied into every consumer,
 * which is what `declared = enforced` exists to prevent.
 *
 * Two names, not one. They arrived carrying the SAME name (`ObjectSchemaLike`)
 * in two files, and they are not the same type: measured with `tsc`, the
 * defaults one is a strict subtype of the child one, and the compiler calls
 * them mutually assignable ONLY because the child one's field values are
 * `any` — swap that single `any` for `unknown` and the child -> defaults
 * direction fails (TS2322). Lifting either under the shared name would have
 * put a name on this package's public surface that already meant something
 * else two files over, with nothing in the name to say which.
 *
 * These are types, not values: they add no runtime surface, and each is the
 * type a signature already published requires — not an adjacent name lifted
 * because it was nearby.
 */
export type { FieldDefaultsSchemaLike } from './schemaDefaults';

// Register object-form component
const ObjectFormRenderer: React.FC<{ schema: any; dataSource?: unknown }> = elementDataSourceBlock(({
  schema,
  dataSource: dataSourceProp,
}) => {
  // ObjectForm needs a dataSource to fetch the object schema and auto-generate
  // its fields. Without one, an `object-form` rendered straight through
  // SchemaRenderer (e.g. the Studio view preview) has no fields.
  //
  // Resolved through the family's shared rule (objectui#5378): an explicit
  // adapter first, the `SchemaRendererProvider` context second. The explicit
  // half is additive — this block used to read context ONLY, so nothing that
  // worked before resolves differently now; what changes is that the three
  // blocks in the family no longer answer "where does the adapter come from?"
  // three different ways, which is the split that made the getting-started
  // guide satisfiable by neither wiring.
  const dataSource = useResolvedDataSource<DataSource>(dataSourceProp);
  // The spec's `PageComponentSchema.dataSource` binding (objectstack#6953). A
  // page that declared `dataSource: { object }` and no `objectName` rendered a
  // field-less shell: `ObjectForm` gates its whole schema fetch on `objectName`.
  //
  // `object` is the ONLY key of the binding this block can honour, and the
  // mapping says so rather than parking the rest somewhere plausible. A form
  // edits ONE record — it has no collection query, so there is nothing for
  // `filter` / `sort` / `limit` to narrow, and a saved LIST view's columns are
  // not a form layout (`fields` here is an ordered layout, not a projection).
  // A `view` name is still resolved, so naming one that does not exist reports
  // instead of rendering; a view that DOES resolve contributes nothing on this
  // block, which is recorded as the residual gap on objectstack#6953.
  return (
    <ElementDataSourceGate
      schema={schema}
      dataSource={dataSource}
      testId="object-form"
      errorTitle="This form’s data source could not be resolved"
      // `ObjectForm` builds its fields from the object's metadata, which only an
      // adapter can serve — its own effect calls the branch it comments as
      // "cannot proceed" and then renders a field-less card in silence
      // (objectui#5378 item 2). The one escape hatch HERE is inline
      // `customFields`. ⚠️ This gate is narrower than the components: every
      // layout, `simple` included since objectui#11615, treats the shared
      // `hasInlineFieldSource` as its members-only field source — non-empty
      // `customFields`, OR sections whose every entry is an inline `FormField`
      // — so a form with an `objectName`, no adapter and all-inline sections is
      // refused here although any layout would draw it as a collector. Not
      // aligned in that card on purpose (it would move this door's behaviour);
      // the two are known to be out of step for that shape. A form with no
      // `objectName` is a different defect, answered by `requiresObject` below.
      requiresDataSource={
        !(schema?.customFields?.length > 0)
        && typeof schema?.objectName === 'string'
        && schema.objectName.length > 0
      }
      noDataSourceMessage={noDataSourceMessage('object-form', schema?.objectName)}
      // A form that names its object in neither place (objectui#11605) drew a
      // field-less card with Cancel and Update buttons. A form whose fields are
      // declared inline is a target-less collector and needs no object: the
      // shared `hasInlineFieldSource` answers that for every variant, both
      // non-empty `customFields` and the sectioned variants' fully-inline
      // `sections` (objectui#10254).
      requiresObject={!hasInlineFieldSource(schema)}
    >
      {(bound) => <ObjectForm schema={bound} dataSource={dataSource} />}
    </ElementDataSourceGate>
  );
});

/**
 * The `objectName` input `object-form` and `view:form` publish (one renderer,
 * one declaration). NOT required, as on the spec row (objectui#11605):
 * `ComponentPropsMap['object-form']` leaves `objectName` optional "because the
 * component-level `dataSource` binding can supply the object instead", and
 * `ObjectFormRenderer` lands `dataSource.object` here. The page compile reads
 * this list, so `required: true` refused a bound node the row and the renderer
 * accept. A node with neither is answered by the gate's "no object named" hint.
 */
const OBJECT_FORM_OBJECT_NAME_INPUT: ComponentInput = {
  name: 'objectName',
  type: 'string',
  description:
    'Object this form creates or edits. Not required: the node\'s `dataSource` binding can name the object instead, and `dataSource.object` lands on this key, outranking an authored value. With neither, and no inline fields (non-empty `customFields`, or `sections` whose every field is inline), the form shows a hint naming this key instead of a form with no fields.',
};

ComponentRegistry.register('object-form', ObjectFormRenderer, {
  namespace: 'plugin-form',
  label: 'Object Form',
  category: 'plugin',
  inputs: [
    { ...OBJECT_FORM_OBJECT_NAME_INPUT },
    { name: 'fields', type: 'array', description: 'Bare field names to show, in order (each looked up in the object schema). NOT the same vocabulary as `sections[].fields`, which also accepts the spec `FormFieldSchema` object (identity key `field`, e.g. `{ field: "note", colSpan: 2 }`) — that shape resolves to no name HERE and is silently skipped (SimpleObjectForm in ObjectForm.tsx; buildFlatFields in flatFields.ts for the drawer/modal presentations).' },
    { name: 'mode', type: 'enum', enum: ['create', 'edit', 'view'] },
    { name: 'formType', type: 'enum', enum: ['simple', 'tabbed', 'wizard', 'split', 'drawer', 'modal'] },
    { name: 'sections', type: 'array' },
    // The row's seven `I18nLabel` members (`ComponentPropsMap['object-form']`):
    // `title`, `description` here, and `submitText`, `cancelText`, `nextText`,
    // `prevText` and `successMessage` below. `ObjectForm` resolves a map with
    // `pickLocalized` against the active UI language, above its `formType` fork
    // (objectui#10993). So both arms are declared, in the same change that taught
    // the render site to resolve the map, as `ComponentInput.type` prescribes: a
    // `'string'`-only declaration made the manifest gate report `type-mismatch`
    // on a legal map. The render is pinned by `ObjectForm.i18nLabels.test.tsx`,
    // the manifest by the console's `objectFormI18nLabelManifest.test.ts`.
    {
      name: 'title',
      type: ['string', 'object'],
      description:
        'Heading of the drawer and modal presentations (`formType: "drawer"` / `"modal"`). Accepts either a plain string or an inline per-locale map (`{ en: "New order", "zh-CN": "新建订单" }`) — the `I18nLabel` union the contract admits on this key — and the form resolves the map against the active UI language, falling back through base language, a region-qualified sibling, `default`, then `en`, and finally to any remaining entry.',
    },
    {
      name: 'description',
      type: ['string', 'object'],
      description:
        'Subtitle under the drawer and modal heading. Accepts either a plain string or an inline per-locale map (`{ en: "Enter the order details", "zh-CN": "填写订单信息" }`), resolved against the active UI language with the same fallback chain as `title`.',
    },
    // `inline` / `grid` RETIRED (objectui#11168 slice 3, objectui#7759 group C):
    // `@objectstack/spec` 17.5.0's row refuses both (objectstack#20221), and
    // measured through the real `SchemaRenderer` both rendered byte-identical
    // to `vertical` — every layout folded them away. The authored bag already
    // refused them by reference to the row; this publishes what it accepts.
    { name: 'layout', type: 'enum', enum: ['vertical', 'horizontal'], description: 'Label placement: `vertical` puts each label above its field (the default), `horizontal` beside it.' },
    { name: 'columns', type: 'number' },
    // Tabbed
    { name: 'defaultTab', type: 'string' },
    { name: 'tabPosition', type: 'enum', enum: ['top', 'bottom', 'left', 'right'] },
    // Wizard
    { name: 'allowSkip', type: 'boolean' },
    { name: 'showStepIndicator', type: 'boolean' },
    // Split
    { name: 'splitDirection', type: 'enum', enum: ['horizontal', 'vertical'] },
    { name: 'splitSize', type: 'number' },
    { name: 'splitResizable', type: 'boolean' },
    // Drawer
    { name: 'drawerSide', type: 'enum', enum: ['top', 'bottom', 'left', 'right'] },
    { name: 'drawerWidth', type: 'string' },
    // Modal
    { name: 'modalSize', type: 'enum', enum: ['sm', 'default', 'lg', 'xl', 'full'] },
    { name: 'modalCloseButton', type: 'boolean', description: 'Show the modal presentation’s close (X) button. Default `true`; `false` hides it. Forwarded by `ObjectForm`’s modal route and honoured by `ModalForm` on both of its dialog arms. With the button hidden the modal still closes on Escape, and on the Cancel action when that is shown.' },
    { name: 'contentLayout', type: 'enum', enum: ['simple', 'tabbed'], description: 'How the modal presentation lays out sections. `tabbed` differs from `simple` only when more than one section has a field to show (`ModalForm` tests `schema.contentLayout === "tabbed" && groups.length > 1`).' },
    { name: 'confirmOnDiscard', type: 'boolean', description: 'Ask before discarding unsaved edits when a drawer/modal form is dismissed. Set `false` to close immediately.' },
    // Record binding
    { name: 'recordId', type: 'string', description: 'The record to load in `edit` / `view` mode. Leave unset for `create`.' },
    { name: 'customFields', type: 'array', description: 'Field definitions merged over the set generated from object metadata. With inline definitions and no data source, this becomes the only field source.' },
    { name: 'initialValues', type: 'object', description: 'Values to prefill in `create` mode.' },
    { name: 'initialData', type: 'object', description: 'Alternate spelling of `initialValues` that the drawer/modal presentations read FIRST — PER MEMBER (`{ ...initialValues, ...initialData }`), so a member this key says nothing about keeps its `initialValues` value. Prefer `initialValues` in new schemas.' },
    { name: 'readOnly', type: 'boolean', description: 'Render every field read-only, whatever `mode` says.' },
    // Buttons
    {
      name: 'submitText',
      type: ['string', 'object'],
      description:
        'Label of the Save button. A map no locale limb resolves shows the default label. Accepts either a plain string or an inline per-locale map (`{ en: "Save order", "zh-CN": "保存订单" }`), resolved against the active UI language with the same fallback chain as `title`.',
    },
    {
      name: 'cancelText',
      type: ['string', 'object'],
      description:
        'Label of the Cancel button. Accepts either a plain string or an inline per-locale map (`{ en: "Back", "zh-CN": "返回" }`), resolved against the active UI language with the same fallback chain as `title`.',
    },
    {
      name: 'nextText',
      type: ['string', 'object'],
      description:
        'Label of the next-step button (wizard). Accepts either a plain string or an inline per-locale map (`{ en: "Continue", "zh-CN": "继续" }`), resolved against the active UI language with the same fallback chain as `title`.',
    },
    {
      name: 'prevText',
      type: ['string', 'object'],
      description:
        'Label of the previous-step button (wizard). Accepts either a plain string or an inline per-locale map (`{ en: "Previous", "zh-CN": "上一步" }`), resolved against the active UI language with the same fallback chain as `title`.',
    },
    { name: 'showSubmit', type: 'boolean' },
    { name: 'showCancel', type: 'boolean' },
    { name: 'showReset', type: 'boolean' },
    // After a successful submit
    { name: 'submitBehavior', type: 'object', description: 'Declarative post-submit behaviour, one of `{ kind: "thank-you", title?, message? }`, `{ kind: "redirect", url, delayMs? }`, `{ kind: "continue" }`, `{ kind: "next-record" }`. When present it takes precedence over `successMessage` / `navigateOnSuccess` / `resetOnSuccess`.' },
    {
      name: 'successMessage',
      type: ['string', 'object'],
      description:
        'Toast shown after a successful submit. Ignored when `submitBehavior` or `navigateOnSuccess` is set. Accepts either a plain string or an inline per-locale map (`{ en: "Order saved", "zh-CN": "订单已保存" }`), resolved against the active UI language with the same fallback chain as `title`.',
    },
    { name: 'navigateOnSuccess', type: 'string', description: 'Path to navigate to after a successful create/update. Supports `{id}` / `{recordId}` interpolation from the saved record and is same-origin-guarded. Takes precedence over `successMessage`.' },
    { name: 'resetOnSuccess', type: 'boolean', description: 'Clear the form after a successful submit instead of keeping the saved values.' },
    // Mobile
    { name: 'mobile', type: 'object', description: 'Phone-only presentation overrides, e.g. `{ stepper: "auto", stepperMinFields: 8, fullscreenLongText: true }`.' },
  ]
});

// Register as view:form for the standard view protocol
// This allows using { type: 'view:form', objectName: '...' } in schemas
// skipFallback prevents overwriting the basic 'form' component from @object-ui/components
ComponentRegistry.register('form', ObjectFormRenderer, {
  namespace: 'view',
  skipFallback: true,
  label: 'Data Form View',
  category: 'view',
  inputs: [
    { ...OBJECT_FORM_OBJECT_NAME_INPUT },
    { name: 'fields', type: 'array', description: 'Bare field names to show, in order (each looked up in the object schema). NOT the same vocabulary as `sections[].fields`, which also accepts the spec `FormFieldSchema` object (identity key `field`, e.g. `{ field: "note", colSpan: 2 }`) — that shape resolves to no name HERE and is silently skipped (this renders through the same `ObjectFormRenderer` / `SimpleObjectForm` as `object-form` above — see its `fields` description).' },
    { name: 'mode', type: 'enum', enum: ['create', 'edit', 'view'] },
  ]
});

// Note: 'form' type (without namespace) is handled by @object-ui/components Form component
// This plugin registers as 'view:form' (with view namespace) for the view protocol
// ObjectForm internally uses { type: 'form' } to render the basic Form component

// Register embeddable-form component for standalone public forms
import { EmbeddableForm } from './EmbeddableForm';

const EmbeddableFormRenderer: React.FC<{ schema: any }> = elementDataSourceBlock(({ schema }) => {
  // Same bridge `object-form` above does, and for the same reason (#3144):
  // `EmbeddableForm` needs a dataSource to fetch the object schema — its own
  // comment says so — and `SchemaRenderer` only ever puts one on the context,
  // never on props. Dropping it here meant an `embeddable-form` rendered
  // through the registry declared `objectName` **required** and then had
  // nothing to bind it to, rendering a field-less shell. That is the
  // objectstack#4413 shape; `public-block-binding-reach.test.tsx` is what
  // catches it now.
  //
  // Read AS DECLARED (objectui#7209): no cast between the hook and the value, so
  // a member `SchemaRendererContextType` does not declare is a compile error
  // here rather than a silent `undefined` — pinned for both readers in this
  // file by `schemaRendererContextRead-7209.test.ts`. The declared `null` (no
  // adapter bound) collapses to the one absence `EmbeddableForm`'s optional
  // prop declares, exactly as `MasterDetailFormRenderer` below already does.
  const ctx = useContext(SchemaRendererContext);
  const dataSource = ctx?.dataSource ?? undefined;
  // The spec's `PageComponentSchema.dataSource` binding (objectstack#7121). Same
  // standing, and the same single mapped key, as `object-form` above:
  // `EmbeddableForm` reads `config.objectName` to fetch the object's fields and
  // to `create()` the submission, so a form authored with `dataSource: { object }`
  // and no flat `objectName` rendered a field-less shell that could not submit.
  //
  // `filter` / `sort` / `limit` have no read site on a form that CREATES one
  // record — there is no collection query for them to narrow — and `fields` is an
  // ordered layout, not a projection a list view's columns could fill, so none of
  // them is mapped. A `view` name is still resolved (a typo reports rather than
  // rendering), and a view that does resolve contributes nothing here.
  return (
    <ElementDataSourceGate
      schema={schema}
      dataSource={dataSource}
      testId="embeddable-form"
      errorTitle="This form’s data source could not be resolved"
      // A public form that names its object in neither place has no fields to
      // fetch and no object to `create()` the submission in, and drew an empty
      // form with a Submit button (objectui#11605).
      requiresObject
    >
      {(bound) => <EmbeddableForm config={bound} dataSource={dataSource} />}
    </ElementDataSourceGate>
  );
});

ComponentRegistry.register('embeddable-form', EmbeddableFormRenderer, {
  namespace: 'plugin-form',
  label: 'Embeddable Form',
  category: 'plugin',
  inputs: [
    { name: 'formId', type: 'string', required: true },
    // NOT required (objectui#11605). This block has no `ComponentPropsMap` row;
    // the contract is the binding doc (`content/docs/guide/data-source.md`, "a
    // node bound this way needs no `objectName` of its own"), and
    // `EmbeddableFormRenderer` lands `dataSource.object` here. The page compile
    // reads this list, so `required: true` refused a bound node the renderer
    // accepts. A node with neither is answered by the gate's hint.
    {
      name: 'objectName',
      type: 'string',
      description:
        'Object the form creates a record in. Not required: the node\'s `dataSource` binding can name the object instead, and `dataSource.object` lands on this key, outranking an authored value. With neither, the form shows a hint naming this key instead of a form that cannot submit.',
    },
    { name: 'title', type: 'string' },
    { name: 'description', type: 'string' },
    { name: 'fields', type: 'array', description: 'Bare field names to show, in order (each looked up in the object schema). NOT the same vocabulary as `sections[].fields`, which also accepts the spec `FormFieldSchema` object (identity key `field`, e.g. `{ field: "note", colSpan: 2 }`) — that shape resolves to no name HERE and is silently skipped (`EmbeddableForm` passes this array straight through to `<ObjectForm>` with no `sections`, so it renders through the same `SimpleObjectForm` as `object-form` above — see its `fields` description).' },
    { name: 'allowMultiple', type: 'boolean' },
  ]
});

/**
 * ⛔ The `form-analytics` node type key is RETIRED (objectui#10859 batch 8, phase 2b,
 * the seat's ruling on that card, by the objectui#10393 / objectui#8760 route).
 * `FormAnalytics` itself stays a named export of this package; a host that
 * wants the submission dashboard mounts the React component directly.
 *
 * ## What was here, and why it went
 *
 * `ComponentRegistry.register('form-analytics', FormAnalyticsRenderer, {
 * namespace: 'plugin-form', ... })` — a thin renderer mapping `formId` /
 * `formTitle` / `metrics` onto `FormAnalytics`.
 * It stored both `plugin-form:form-analytics` and the bare `form-analytics` fallback.
 * No `@object-ui/types` arm claims it, so `objectui validate` refused a node
 * authored `type: 'form-analytics'` at `type` while the registry mounted it.
 *
 * ## Why unregistering is the whole retirement
 *
 * Nothing wrote the node: 0 producers in source, docs, examples, the catalog
 * or objectstack, and 0 runtime emission, re-measured for phase 2b. The ruling's
 * criterion ("does the mainstream have it?") answered no for a NODE: the
 * mainstream keeps submission analytics inside the forms product, not as an
 * authorable block. The README and `plugin-form.mdx` key-table rows went in
 * the same change.
 */

// Register master-detail composite form (parent + child line items, entered
// together — see ADR-0001).
import { MasterDetailForm } from './MasterDetailForm';

const MasterDetailFormRenderer: React.FC<{ schema: any }> = elementDataSourceBlock(({ schema }) => {
  const ctx = useContext(SchemaRendererContext);
  const dataSource = ctx?.dataSource ?? undefined;
  // The spec's `PageComponentSchema.dataSource` binding (objectstack#7121).
  // `schema.objectName` is the PARENT object here, and everything downstream is
  // gated on it — `deriveDetail` needs it to find each child's relationship field
  // back to the parent, and the parent form/save path names it directly. A
  // master-detail form authored with `dataSource: { object }` and no flat
  // `objectName` therefore rendered a parent shell whose details could not even
  // resolve their own FK.
  //
  // `object` is the only key mapped, and for the same reason as the two forms
  // above: the parent is ONE record (no collection query for `filter` / `sort` /
  // `limit` to narrow) and the child collections are fetched by FK from
  // `schema.details`, at a fixed `$top: 500`, not from anything the binding
  // carries. `details[].columns` is a per-child editable grid spec, not a
  // projection a saved view could supply.
  return (
    <ElementDataSourceGate
      schema={schema}
      dataSource={dataSource}
      testId="object-master-detail-form"
      errorTitle="This form’s data source could not be resolved"
      // With no parent object in either place there is no parent form to draw
      // and no relationship to derive: it drew an empty parent and a detail
      // hint about a missing link to a blank parent (objectui#11605).
      requiresObject
    >
      {(bound) => <MasterDetailForm schema={bound} dataSource={dataSource} />}
    </ElementDataSourceGate>
  );
});

ComponentRegistry.register('object-master-detail-form', MasterDetailFormRenderer, {
  namespace: 'plugin-form',
  label: 'Master-Detail Form',
  category: 'plugin',
  inputs: [
    // NOT required, as on the spec row (objectui#11605):
    // `ComponentPropsMap['object-master-detail-form']` leaves the PARENT
    // `objectName` optional "because the component-level `dataSource` binding
    // can supply the object instead", and `MasterDetailFormRenderer` lands
    // `dataSource.object` here. The page compile reads this list, so
    // `required: true` refused a bound node the row and the renderer accept. A
    // node with neither is answered by the gate's hint.
    {
      name: 'objectName',
      type: 'string',
      description:
        'The PARENT object this form creates or edits. Not required: the node\'s `dataSource` binding can name the object instead, and `dataSource.object` lands on this key, outranking an authored value. With neither, the form shows a hint naming this key instead of an empty parent form.',
    },
    { name: 'mode', type: 'enum', enum: ['create', 'edit'] },
    { name: 'sections', type: 'array' },
    // `of: 'object'` is DERIVED from the contract, as `ComponentInput.of`
    // prescribes (objectui#11396): since `@objectstack/spec` 17.6.0 the row's
    // `details` member is a closed object entry (objectstack-ai/objectstack#21215),
    // the one coarse kind the spec accepts there, and the console parity gate's
    // member direction witnesses the declaration against the spec row. The
    // entry's TypeScript face is `MasterDetailDetailConfig`, derived from the
    // same spec entry by reference (MasterDetailForm.tsx).
    {
      name: 'details',
      type: 'array',
      of: 'object',
      required: true,
      description:
        'The child collections, one OBJECT per entry, judged by the spec\'s closed `details` entry: `childObject` (required) names the child object; `relationshipField` is the FK on the child back to the parent, derived from the child\'s metadata when omitted; `columns` are the line grid\'s columns as the spec\'s inline grid column objects (`{ name, … }`, never a bare field name), derived from the child\'s fields when omitted; `formFields` names the per-row form\'s fields; `inlineMode` is `grid` (editable cells) or `form` (list + per-row form); `amountField` is the CHILD column summed and `totalField` the PARENT field that sum is saved to; `title`, `minRows`, `maxRows` and `addLabel` dress the section and its grid. An undeclared member key is refused by name. The entry\'s `sortField` is read by nothing here — the line-position field is derived from the child object (objectui#11070) — and objectstack retires the key on its `main` (objectstack-ai/objectstack#21589, after 17.6.0).',
    },
    { name: 'recordId', type: 'string', description: 'The parent record to load in `edit` mode. Leave unset for `create`.' },
    // TWO values, not the six `object-form` declares (objectui#5939). A bare
    // `string` here let an out-of-vocabulary value match NO renderer branch and
    // fall through to the flat field list with no diagnostic — measured: a
    // `formType` of `'wizzard'` renders the parent half with its section headers
    // silently gone. The vocabulary is narrowed to what the master-detail
    // composition actually supports, which the repo already states twice:
    // `MasterDetailFormSchema.formType?: 'simple' | 'tabbed'`
    // (MasterDetailForm.tsx) and the coercion `formType === 'tabbed' ? 'tabbed'
    // : 'simple'` ObjectForm.tsx uses when it routes a `subforms` schema in here.
    // The other four are reachable branches that BREAK this composition, each
    // observed rather than assumed: `drawer`/`modal` host the parent half in a
    // portal dialog outside the master-detail container, so the single bottom
    // Save bar finds no `<form>` to submit; `wizard` mounts only the current
    // step's fields and turns that Save bar into a `Next`; `split` renders two
    // panels but persists through `dataSource.create` instead of the batch.
    // Declaring them would mint choices an authoring UI offers and this block
    // cannot honour.
    { name: 'formType', type: 'enum', enum: ['simple', 'tabbed'], description: 'How the PARENT half of the form is presented. The detail grids below it are unaffected.' },
    { name: 'fields', type: 'array', description: 'Which parent fields to show, in order — and it is NOT ignored when `sections` is given: the two INTERSECT. The parent field pool is built from this key first and every section then resolves its NAMED members (a bare name, or the `{ field }` entry) against that pool, so such a member this key does not list is dropped from the rendered form, and a section that loses EVERY member that way disappears with its heading. An inline field entry (`{ name, type, … }`) names nothing to resolve and is drawn whatever this key lists, as on every form type (objectui#11615). Each such drop is reported once via `console.warn` (objectui#9884); it is not repaired, because this key bounds what the form DRAWS and edits, not what Save writes: on a create, the submitted set is the drawn fields plus any parent value seeded through `initialValues` (or its alternate spelling `initialData`), drawn or not. A seed for an undeclared, server-owned, computed or read-only field is still stripped, as on any save. Author one or the other, or list every section member here too. Members are bare field names; NOT the spec `FormFieldSchema` object `sections[].fields` accepts (identity key `field`) — that shape resolves to no name here and is silently skipped (the parent form renders through the same `ObjectForm` / `SimpleObjectForm` as `object-form` — see its `fields` description).' },
    // The three labels are the spec's `I18nLabel` (`ComponentPropsMap
    // ['object-master-detail-form']`), and `MasterDetailForm` resolves a map
    // with `pickLocalized` against the active UI language (objectui#10935). So
    // both arms are declared, in the same change that taught the render site to
    // resolve the map, as `ComponentInput.type` prescribes: a `'string'`-only
    // declaration made the manifest gate report `type-mismatch` on a legal map.
    // The render is pinned by `MasterDetailForm.i18nLabels.test.tsx`, the
    // manifest by the console's `masterDetailFormI18nLabelManifest.test.ts`.
    {
      name: 'title',
      type: ['string', 'object'],
      description:
        'Names the record in the built-in "… saved" toast after an edit save, which shows only when the host supplies no `onSuccess`. Accepts either a plain string or an inline per-locale map (`{ en: "Purchase order", "zh-CN": "采购单" }`) — the `I18nLabel` union the contract admits on this key — and the renderer resolves the map against the active UI language, falling back through base language, a region-qualified sibling, `default`, then `en`, and finally to any remaining entry.',
    },
    {
      name: 'submitText',
      type: ['string', 'object'],
      description:
        'Label of the button that saves the parent and every detail row in one batch. Defaults to "Save" when editing a record (`mode: "edit"` with a `recordId`) and to "Create" otherwise, in the active UI language; an empty string, or a map no locale limb resolves, shows the default too. Accepts either a plain string or an inline per-locale map (`{ en: "Save order", "zh-CN": "保存订单" }`), resolved against the active UI language with the same fallback chain as `title`.',
    },
    {
      name: 'cancelText',
      type: ['string', 'object'],
      description:
        'Label of the Cancel button, which renders only when the host supplies an `onCancel` callback (a runtime slot, not authorable in a JSON document). Defaults to "Cancel", in the active UI language; an empty string, or a map no locale limb resolves, shows the default too. Accepts either a plain string or an inline per-locale map (`{ en: "Back", "zh-CN": "返回" }`), resolved against the active UI language with the same fallback chain as `title`.',
    },
    { name: 'showSubmit', type: 'boolean' },
    { name: 'initialValues', type: 'object', description: 'Values to prefill on the PARENT record in `create` mode.' },
    { name: 'initialData', type: 'object', description: 'Alternate spelling of `initialValues` the renderer also reads: the `parentSchema` memo carries both keys onto the parent form, which merges them PER MEMBER with this one winning. Prefer `initialValues` in new schemas.' },
    { name: 'taxRateField', type: 'string', description: 'Name of the field ON THE CHILD object that holds each line’s tax rate. Feeds the line-items totals row; leave unset when the detail rows carry no tax.' },
  ],
});

// Register record:line_items — child grid bound to an existing parent record,
// usable on a record/detail page or slotted slot.
import { LineItemsPanel } from './LineItemsPanel';

/**
 * `record:line_items` is the one block in this batch whose object does NOT live
 * under `objectName`: the collection it lists, fetches and writes is
 * `schema.childObject` (`LineItemsPanel.tsx` — `dataSource.find(schema.childObject,
 * …)`, `getObjectSchema(schema.childObject)`, and the child leg of the save
 * batch). So the binding's `object` maps THERE, the same way it maps onto
 * `record:related_list`'s `objectName` — in both blocks that key names the CHILD
 * object the panel is bound to, which is what `dataSource.object` means.
 *
 * `filter` / `sort` / `limit` map too, since objectstack#7137 gave the panel's
 * fetch read sites for all three: the composed filter is AND-combined with the
 * parent relationship condition (never substituted for it — a line-items panel is
 * always scoped to the record it sits on, so an *additional* criterion can only
 * narrow this parent's children), `sort` becomes the load order, and `limit` the
 * row cap that used to be a fixed `$top: 500`.
 *
 * Two things are still NOT mapped, each for a reason rather than an oversight:
 *
 *  - `relationshipField` stays the author's: it is not part of the binding, and it
 *    must name a field ON the bound child object. Rebinding `object` without
 *    updating it is an authoring error the panel cannot paper over.
 *  - `columns` is NOT a field-name projection here. It is `GridColumn[]`
 *    (`{ name, type, options, computed, expr, … }`) driving an EDITABLE grid; a
 *    saved view's column list would arrive as bare names and render a grid of
 *    column definitions with no `name`. Wrong shape, not merely a wider answer.
 *
 * So a `view` named on this block now contributes its filter, sort and page size
 * to the child query (and an unresolvable name still reports instead of silently
 * widening), while its column list stays out — the one thing whose shape does not
 * fit this grid.
 */
const RECORD_LINE_ITEMS_DATA_SOURCE: ElementDataSourceMapping = {
  object: 'childObject',
  filter: true,
  sort: true,
  limit: 'limit',
};

const LineItemsPanelRenderer: React.FC<{ schema: any }> = elementDataSourceBlock(({ schema }) => (
  // The spec's `PageComponentSchema.dataSource` binding (objectstack#7121). No
  // `dataSource` is passed: the gate falls back to `SchemaRendererContext`, which
  // is the very adapter `LineItemsPanel` loads its rows through — resolving `view`
  // against a different source than the rows come from could report a view as
  // missing on a host that has it.
  <ElementDataSourceGate
    schema={schema}
    mapping={RECORD_LINE_ITEMS_DATA_SOURCE}
    testId="record-line-items"
    errorTitle="This line-items panel’s data source could not be resolved"
  >
    {(bound) => <LineItemsPanel schema={bound} />}
  </ElementDataSourceGate>
));

ComponentRegistry.register('line_items', LineItemsPanelRenderer, {
  namespace: 'record',
  skipFallback: true,
  label: 'Line Items',
  category: 'record',
  // Mirrors `@objectstack/spec` `RecordLineItemsProps` (17.6.0), key for key.
  //
  // The ten keys after `amountField` were DECLARED by objectui#11536, each by
  // measurement rather than by copying the row: every one is authored in the
  // spec's `{ type, properties }` form through the real `SchemaRenderer` and
  // this registration, beside a control without it, and every one moves the
  // panel (`__tests__/lineItemsDeclaredInputs-11536.test.tsx`). `filter` /
  // `sort` / `limit` are read as TOP-LEVEL keys, not only as `dataSource`
  // members: with no binding the gate hands the schema through untouched and
  // `LineItemsPanel` reads them itself; with one, the gate composes them with
  // the binding before the panel reads them. A key the panel does not read is
  // not declared here, and none of the row's fifteen is such a key.
  //
  // `childObject` is NOT required, as on the row (objectui#11569): the node's
  // `dataSource` binding can supply it, and the page compile reads this list,
  // so `required: true` here refused a bound node the row and the renderer
  // accept. The manifest has no "one of these is required" form, so a node
  // with neither is left to the panel's configuration hint.
  inputs: [
    {
      name: 'childObject',
      type: 'string',
      description:
        'The child object whose records the panel lists, edits and saves. Not required: the node\'s `dataSource` binding can name the object instead, and `dataSource.object` lands on this key, outranking an authored value. With neither, the panel shows a configuration hint naming this key and loads nothing.',
    },
    { name: 'relationshipField', type: 'string', required: true },
    { name: 'columns', type: 'array', required: true },
    { name: 'totalField', type: 'string' },
    { name: 'amountField', type: 'string' },
    {
      name: 'parentObject',
      type: 'string',
      description:
        'The PARENT object the line total is written to on Save, together with `totalField`. Defaults to the object of the record the page shows, and outranks it when set. With neither, Save writes the lines alone and no parent field.',
    },
    {
      name: 'parentId',
      type: 'string',
      description:
        'The parent record whose lines the panel lists and saves: it loads `childObject` rows whose `relationshipField` equals this id, and a line added in the grid is saved with this id in `relationshipField`. Outranks `recordId` and the record the page shows; leave it unset on a record page, where the record shown is the parent. With no parent id at all the panel asks the user to save the record first and loads nothing.',
    },
    {
      name: 'recordId',
      type: 'string',
      description:
        'The parent record id, read only when `parentId` is unset. It outranks the record the page shows.',
    },
    {
      name: 'title',
      type: 'string',
      description:
        'Heading of the panel. Defaults to "Line Items" in the active UI language. A plain string, drawn as authored.',
    },
    {
      name: 'readonly',
      type: 'boolean',
      description:
        'Shows the lines without editing: no Save button, no Add line / Duplicate row / Remove row actions, and the grid draws a read-only table.',
    },
    {
      name: 'minRows',
      type: 'number',
      description:
        'Fewest lines the user can leave: every line\'s Remove row action is disabled while the grid holds this many lines or fewer. It adds no blank lines to reach the number.',
    },
    {
      name: 'maxRows',
      type: 'number',
      description:
        'Most lines the user can hold: at this many lines Add line and Duplicate row are disabled and the trailing blank entry row is not drawn.',
    },
    {
      name: 'filter',
      type: 'array',
      of: 'object',
      description:
        'Additional criteria for the lines, as spec `ViewFilterRule` entries (`[{ field, operator, value }]`). AND-combined with the parent relationship condition, never a replacement for it: it can only narrow this record\'s lines. Also the key a per-element `dataSource` binding\'s composed filter lands on.',
    },
    {
      name: 'sort',
      type: 'array',
      of: 'object',
      description:
        'Load order for the lines, as `[{ field, order }]` entries applied in list order; `order` is `asc` or `desc`. Without it the lines arrive in storage order.',
    },
    {
      name: 'limit',
      type: 'number',
      description:
        'Most lines loaded (default 500). The grid has no pagination: every loaded line is editable and saved as one batch, and lines past the cap are not loaded. Must be a positive integer: any other value is ignored, with a console warning.',
    },
  ],
});
